#!/usr/bin/env bash
# Configures the domain zone so that the subdomain www points to my load-balancer IP
if [ $# -eq 1 ]
then
	sub_domains=("www"
	    "lb-01"
	    "web-01"
	    "web-02")
else
	sub_domains=$2
fi

for i in "${sub_domains[@]}" # loops through list of subdomains
do
    dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The sub domain "$i" is a "$4" record and points to "$5}'
done

