#!/usr/bin/env bash
# Configures the domain zone so that the subdomain www points to my load-balancer IP

sub_domains=("www"
    "lb-01"
    "web-01"
    "web-02")

SUBDOMAIN()
{
    for i in "${sub_domains[@]}"
    do
	echo -n "The sub domain $i"
	dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print " is a "$4" record and points to "$5}'
    done
}

if [ $# == 2 ]
then
    echo -n "The sub domain $2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print " is a "$4" record and points to "$5}'
else
    SUBDOMAIN "$1"
fi
