#!/usr/bin/env bash
# Installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sudo sed -i "location /redirect_me {\n\t\trewrite ^/(.*)redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n" /etc/nginx/sites-available/default
sudo service nginx start
