#!/usr/bin/env bash
# Configures Nginx server to have custom 404
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > root /var/www/html/index.html
sudo sed -i "s|server_name\ _;|server_name _;\n\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > root /var/www/html/404.html
sudo sed -i "35i error_page 404 /error_404.html;\nlocation = /error_404.html {\nroot /var/www/html/;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx start
