#!/usr/bin/env bash
# Doubles the number of webservers
sudo apt -y update
sudo apt -y install nginx
sudo sed -i "32i\\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
