#!/usr/bin/env bash
#Installs and configures HAproxy
sudo apt -y update
sudo apt -y install haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "$ a\ \nfrontend http_front\n\t bind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 1107-web-01 35.243.212.54:80 check\n\tserver 1107-web-02 3.88.185.245:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
