#!/usr/bin/env bash
# Gives you information about the holbertonschool file
File=holbertonschool
if [[ -a "$File" ]];
then
    echo "$File file exists"
else
    echo "$File file does not exist"
    if [[ -s "$File" ]];
    then
	echo "$File file is not empty"
    else
	echo "$File file is empty"
    fi
    if [[ -f "$File" ]];
    then
	echo "$File is a regular file"
    fi
fi
