#!/usr/bin/env bash
# Reloads Nginx as user Nginx on 8080
chmod 744 /etc/nginx/nginx.conf  
sudo pkill apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx reload